targets:
  $default:
    builders:
      riverpod_generator:
        generate_for:
          - '**/application/**.dart'
          - 'lib/src/router/router.dart'
      go_router_builder:
        generate_for:
          - 'lib/src/router/router.dart'
      graphql_codegen:
        options:
          clients:
            - graphql